with open("sen-sms.html","r",encoding="utf-8") as f:
    c=f.read()
if "auth-overlay" in c:
    print("deja patche")
else:
    auth_css='<style>\n#auth-overlay{position:fixed;inset:0;z-index:9999;background:linear-gradient(135deg,#0A0A0A,#1A0F00);display:flex;align-items:center;justify-content:center;font-family:sans-serif}#auth-overlay.hidden{display:none}.auth-box{background:#111;border:1px solid rgba(245,158,11,.2);border-radius:20px;padding:48px 40px;width:100%;max-width:420px}.auth-logo{display:flex;align-items:center;gap:12px;margin-bottom:32px;justify-content:center}.auth-logo-s{width:48px;height:48px;background:#F59E0B;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:900;color:#0A0A0A}.auth-logo-name{font-size:22px;font-weight:700;color:#fff}.auth-logo-name span{color:#F59E0B}.auth-tabs{display:flex;background:#1A1A1A;border-radius:10px;padding:4px;margin-bottom:28px}.auth-tab{flex:1;padding:10px;text-align:center;border-radius:8px;cursor:pointer;font-size:14px;font-weight:600;color:#666;transition:all .2s}.auth-tab.active{background:#F59E0B;color:#0A0A0A}.auth-field{margin-bottom:16px}.auth-field label{display:block;font-size:12px;font-weight:600;color:#888;margin-bottom:6px;text-transform:uppercase}.auth-field input{width:100%;padding:12px 16px;background:#1A1A1A;border:1px solid #2A2A2A;border-radius:10px;color:#fff;font-size:14px;outline:none}.auth-field input:focus{border-color:#F59E0B}.auth-btn{width:100%;padding:14px;background:#F59E0B;color:#0A0A0A;border:none;border-radius:10px;font-size:16px;font-weight:700;cursor:pointer;margin-top:8px}.auth-error{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.3);color:#FCA5A5;border-radius:8px;padding:10px 14px;font-size:13px;margin-bottom:14px;display:none}.auth-footer{text-align:center;margin-top:20px;font-size:12px;color:#444}.auth-footer span{color:#F59E0B;cursor:pointer}.auth-user-bar{display:none;align-items:center;gap:10px;padding:8px 16px;background:rgba(245,158,11,.1);border-radius:8px;margin-bottom:16px;border:1px solid rgba(245,158,11,.2)}.auth-user-bar.show{display:flex}.auth-user-name{font-size:13px;font-weight:600;color:#F59E0B;flex:1}.auth-logout-btn{background:transparent;border:1px solid #333;color:#888;font-size:11px;padding:4px 10px;border-radius:6px;cursor:pointer}\n</style>'
    auth_html='<div id="auth-overlay"><div class="auth-box"><div class="auth-logo"><div class="auth-logo-s">S</div><span class="auth-logo-name">Sen<span>SMS</span></spa




Set-Content -Encoding UTF8 patch_auth.py @'
with open("sen-sms.html","r",encoding="utf-8") as f:
    c=f.read()
if "auth-overlay" in c:
    print("deja patche")
else:
    auth_css='<style>\n#auth-overlay{position:fixed;inset:0;z-index:9999;background:linear-gradient(135deg,#0A0A0A,#1A0F00);display:flex;align-items:center;justify-content:center;font-family:sans-serif}#auth-overlay.hidden{display:none}.auth-box{background:#111;border:1px solid rgba(245,158,11,.2);border-radius:20px;padding:48px 40px;width:100%;max-width:420px}.auth-logo{display:flex;align-items:center;gap:12px;margin-bottom:32px;justify-content:center}.auth-logo-s{width:48px;height:48px;background:#F59E0B;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:900;color:#0A0A0A}.auth-logo-name{font-size:22px;font-weight:700;color:#fff}.auth-logo-name span{color:#F59E0B}.auth-tabs{display:flex;background:#1A1A1A;border-radius:10px;padding:4px;margin-bottom:28px}.auth-tab{flex:1;padding:10px;text-align:center;border-radius:8px;cursor:pointer;font-size:14px;font-weight:600;color:#666;transition:all .2s}.auth-tab.active{background:#F59E0B;color:#0A0A0A}.auth-field{margin-bottom:16px}.auth-field label{display:block;font-size:12px;font-weight:600;color:#888;margin-bottom:6px;text-transform:uppercase}.auth-field input{width:100%;padding:12px 16px;background:#1A1A1A;border:1px solid #2A2A2A;border-radius:10px;color:#fff;font-size:14px;outline:none}.auth-field input:focus{border-color:#F59E0B}.auth-btn{width:100%;padding:14px;background:#F59E0B;color:#0A0A0A;border:none;border-radius:10px;font-size:16px;font-weight:700;cursor:pointer;margin-top:8px}.auth-error{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.3);color:#FCA5A5;border-radius:8px;padding:10px 14px;font-size:13px;margin-bottom:14px;display:none}.auth-footer{text-align:center;margin-top:20px;font-size:12px;color:#444}.auth-footer span{color:#F59E0B;cursor:pointer}.auth-user-bar{display:none;align-items:center;gap:10px;padding:8px 16px;background:rgba(245,158,11,.1);border-radius:8px;margin-bottom:16px;border:1px solid rgba(245,158,11,.2)}.auth-user-bar.show{display:flex}.auth-user-name{font-size:13px;font-weight:600;color:#F59E0B;flex:1}.auth-logout-btn{background:transparent;border:1px solid #333;color:#888;font-size:11px;padding:4px 10px;border-radius:6px;cursor:pointer}\n</style>'
    auth_html='<div id="auth-overlay"><div class="auth-box"><div class="auth-logo"><div class="auth-logo-s">S</div><span class="auth-logo-name">Sen<span>SMS</span></span></div><div class="auth-tabs"><div class="auth-tab active" onclick="authSwitchTab(\'login\')">Connexion</div><div class="auth-tab" onclick="authSwitchTab(\'register\')">Cr\u00e9er un compte</div></div><div id="auth-error" class="auth-error"></div><div id="auth-login-form"><div class="auth-field"><label>T\u00e9l\u00e9phone ou Email</label><input type="text" id="auth-login-id" placeholder="+221 77 XXX XX XX"></div><div class="auth-field"><label>Mot de passe</label><input type="password" id="auth-login-pw" placeholder="\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022"></div><button class="auth-btn" onclick="authLogin()">Se connecter \u2192</button></div><div id="auth-register-form" style="display:none"><div class="auth-field"><label>Nom / Organisation</label><input type="text" id="auth-reg-name" placeholder="Ex: \u00c9cole Mariama B\u00e2"></div><div class="auth-field"><label>T\u00e9l\u00e9phone</label><input type="text" id="auth-reg-phone" placeholder="+221 77 XXX XX XX"></div><div class="auth-field"><label>Email</label><input type="email" id="auth-reg-email" placeholder="votre@email.com"></div><div class="auth-field"><label>Mot de passe</label><input type="password" id="auth-reg-pw" placeholder="Minimum 6 caract\u00e8res"></div><button class="auth-btn" onclick="authRegister()">Cr\u00e9er mon compte \u2192</button></div><div class="auth-footer">\ud83c\uddf8\ud83c\uddf3 Sen-SMS \u00b7 <span onclick="authSkip()">Acc\u00e8s d\u00e9monstration</span></div></div></div>\n<div class="auth-user-bar" id="sensms-user-bar"><span>\ud83d\udc64</span><span class="auth-user-name" id="sensms-user-name">Utilisateur</span><button class="auth-logout-btn" onclick="authLogout()">D\u00e9connexion</button></div>'
    auth_js='\nvar sensmsUser=null;\nfunction authSwitchTab(t){document.getElementById("auth-login-form").style.display=t==="login"?"block":"none";document.getElementById("auth-register-form").style.display=t==="register"?"block":"none";document.querySelectorAll(".auth-tab").forEach(function(el,i){el.classList.toggle("active",(i===0&&t==="login")||(i===1&&t==="register"));});document.getElementById("auth-error").style.display="none";}\nfunction authShowError(m){var e=document.getElementById("auth-error");e.textContent=m;e.style.display="block";}\nfunction authLogin(){var id=document.getElementById("auth-login-id").value.trim(),pw=document.getElementById("auth-login-pw").value.trim();if(!id||!pw){authShowError("Remplissez tous les champs");return;}fetch(API+"/api/sensms/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({identifier:id,password:pw})}).then(function(r){return r.json();}).then(function(d){if(d.success){sensmsUser=d.user;localStorage.setItem("sensms_user",JSON.stringify(d.user));authDone();}else{authShowError(d.error||"Identifiants incorrects");}}).catch(function(){authShowError("Erreur reseau");});}\nfunction authRegister(){var name=document.getElementById("auth-reg-name").value.trim(),phone=document.getElementById("auth-reg-phone").value.trim(),email=document.getElementById("auth-reg-email").value.trim(),pw=document.getElementById("auth-reg-pw").value.trim();if(!name||!phone||!pw){authShowError("Champs obligatoires manquants");return;}if(pw.length<6){authShowError("Mot de passe trop court");return;}fetch(API+"/api/sensms/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name,phone:phone,email:email,password:pw})}).then(function(r){return r.json();}).then(function(d){if(d.success){sensmsUser=d.user;localStorage.setItem("sensms_user",JSON.stringify(d.user));authDone();}else{authShowError(d.error||"Erreur inscription");}}).catch(function(){authShowError("Erreur reseau");});}\nfunction authSkip(){sensmsUser={name:"Demo",demo:true};authDone();}\nfunction authDone(){document.getElementById("auth-overlay").classList.add("hidden");if(sensmsUser&&!sensmsUser.demo){var bar=document.getElementById("sensms-user-bar");bar.classList.add("show");document.getElementById("sensms-user-name").textContent=sensmsUser.name||sensmsUser.phone;var o=document.getElementById("org-name");if(o&&!o.value)o.value=sensmsUser.name||"";var p=document.getElementById("org-phone");if(p&&!p.value)p.value=sensmsUser.phone||"";}}\nfunction authLogout(){localStorage.removeItem("sensms_user");sensmsUser=null;document.getElementById("sensms-user-bar").classList.remove("show");document.getElementById("auth-overlay").classList.remove("hidden");}\n(function(){var s=localStorage.getItem("sensms_user");if(s){try{sensmsUser=JSON.parse(s);authDone();}catch(e){localStorage.removeItem("sensms_user");}}})();'
    c=c.replace("</head>",auth_css+"</head>",1)
    c=c.replace("<body>","<body>\n"+auth_html,1)
    last=c.rfind("</script>")
    c=c[:last]+auth_js+"\n</script>"+c[last+9:]
    with open("sen-sms.html","w",encoding="utf-8") as f:
        f.write(c)
    print("OK taille:"+str(len(c)))
